library(hexbin)
library(scatterplot3d)
library(MASS)
library(outliers)
#If there are some interesting or suspicious points in a scatter plot and one wants
#to find out which data records these are, one can do this by
plot(iris$Petal.Width,iris$Petal.Length)
identify(iris$Petal.Width,iris$Petal.Length)

#If symbols representing the values for some categorical attribute should be included
#in a scatter plot, this can be achieved by
plot(iris$Petal.Width,iris$Petal.Length,
       pch=as.numeric(iris$Species))

plot(jitter(iris$Petal.Width),
     jitter(iris$Petal.Length))

#Intensity plots and density plots with hexagonal binning can be generated by
plot(iris$Petal.Width,iris$Petal.Length,col=rgb(0,0,0,50,maxColorValue=255),pch=16)
#and
bin <- hexbin(iris$Petal.Width, iris$Petal.Length, xbins=50)
plot(bin)
#Note that such plots are not very useful for such a small data sets like the Iris data set.

#For three-dimensional scatter plots, the library scatterplots3d is needed and has to be installed first:
scatterplot3d(iris$Sepal.Length, iris$Sepal.Width, iris$Petal.Length)

#PCA can be carried out with R in the following way:
species <- which(colnames(iris)=="Species")
iris.pca <- prcomp(iris[,-species], center=T,scale=T)
print(iris.pca)
summary(iris.pca)
plot(predict(iris.pca))


#For the Iris data set, it is necessary to exclude the categorical attribute Species
#from PCA. This is achieved by the first line of the code and calling prcomp with
#iris[,-species] instead of iris.
#The parameter settings center=T, scale=T, where T is just a short form of
#TRUE, mean that z-score standardization is carried out for each attribute before
#applying PCA.
#The function predict can be applied in the above-described way to obtain
#the transformed data from which the PCA was computed. If the computed PCA
#transformation should be applied to another data set x, this can be achieved by
predict(iris.pca,newdata=x)
#where x must have the same number of columns as the data set from which the PCA
#has been computed. In this case, x must have four columns which must be numerical.
#predict will compute the full transformation, so that the above command
#will also yield transformed data with four columns.


#Parallel coordinates need the library MASS. All attributes must be numerical. If the
#attribute Species should be included in the parallel coordinates, one can achieve this
#in the following way:
x <- iris
x$Species <- as.numeric(iris$Species)
parcoord(x)

#Star and radar plots are obtained by the following two commands:
stars(iris)
stars(iris,locations=c(0,0))

#Pearson's, Spearman's, and Kendall's correlation coefficients are obtained by the
#following three commands:
cor(iris$Sepal.Length,iris$Sepal.Width)
cor.test(iris$Sepal.Length,iris$Sepal.Width,method="spearman")
cor.test(iris$Sepal.Length,iris$Sepal.Width,method="kendall")

#Grubb's test for outlier detection needs the installation of the library outliers:
grubbs.test(iris$Petal.Width)
